id: P03DFD415
initial_creation_type: ocr
source_metadata:
  volumes:
    d49b1cc0ffa341a1a3dc4da4d7f5c12f:
      base_file: v096.txt
      image_group_id: I1PD95941
      title: ཡོན་ཏན་བདུན་ཡོངས་སུ་བརྗོད་པའི་གཏམ།
      total_pages: 1144
      volume_number: 96
